# Generated by Django 3.2.2 on 2021-05-07 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duedate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
