# Generated by Django 3.2.2 on 2021-05-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_post_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='duedate',
            field=models.CharField(max_length=255),
        ),
    ]
