# Generated by Django 3.2 on 2021-05-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_auto_20210502_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
